<h1 align="center"><b>Исследование сетевых параметров публичных DNS серверов</b></h1>
------------------------------------
### **Цель работы**

Проанализировать сетевые параметры публичных DNS серверов, сделать мотивированный вывод о предпочтительных серверах

### **Используемое ПО**

* Rstudio IDE
* Traceroute/tracert
* Ping
* 2ip

### **Исследуемые провайдеры DNS**

* Google Public DNS
* Cloudflare DNS
* OpenDNS
* FLEX

### **Варианты решения задачи**

* Простой поиск
* Утилита tracert/traceroute

### **План выполнения**

1. По исследуемым серверам собрать следующие данные:
    * маршрут 
    * местоположение каждого узла маршрута к DNS-серверу 
    * организацию, владеющую каждым узлом маршрута к DNS-серверу 
    * среднюю RTT к DNS-серверу
2. Выделить те узлы маршрута, которые вносят наибольшую временную задержку при передаче
3. Сравнить сетевые параметры DNS серверов

### **Ход работы**

<h3 align="center"><b>Google DNS</b></h3>

**Маршрут**


```
>tracert 8.8.8.8

Трассировка маршрута к dns.google [8.8.8.8]
с максимальным числом прыжков 30:

  1     3 ms     2 ms     2 ms  router.asus.com [192.168.1.1]
  2     3 ms     3 ms     3 ms  10.224.0.1
  3    32 ms    20 ms     4 ms  msk.piter-ix.google.com [31.44.187.11]
  4     7 ms     5 ms     4 ms  108.170.250.83
  5    18 ms    17 ms    17 ms  216.239.50.2
  6    19 ms    18 ms    18 ms  108.170.232.251
  7    19 ms    19 ms    16 ms  172.253.79.237
  8     *        *        *     Превышен интервал ожидания для запроса.
  9     *        *        *     Превышен интервал ожидания для запроса.
 10     *        *        *     Превышен интервал ожидания для запроса.
 11     *        *        *     Превышен интервал ожидания для запроса.
 12     *        *        *     Превышен интервал ожидания для запроса.
 13     *        *        *     Превышен интервал ожидания для запроса.
 14     *        *        *     Превышен интервал ожидания для запроса.
 15     *        *        *     Превышен интервал ожидания для запроса.
 16     *        *        *     Превышен интервал ожидания для запроса.
 17    19 ms    17 ms    19 ms  dns.google [8.8.8.8]

Трассировка завершена.

```
**Среднее RTT**
```
>ping 8.8.8.8

Обмен пакетами с 8.8.8.8 по с 32 байтами данных:
Ответ от 8.8.8.8: число байт=32 время=18мс TTL=48
Ответ от 8.8.8.8: число байт=32 время=18мс TTL=48
Ответ от 8.8.8.8: число байт=32 время=20мс TTL=48
Ответ от 8.8.8.8: число байт=32 время=20мс TTL=48

Статистика Ping для 8.8.8.8:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 18мсек, Максимальное = 20 мсек, Среднее = 19 мсек
  
```
Наибольшая задержка у 3 и 4 узла.

**Местоположение и организация**

|  №    |              Узел                       |     Местоположение      |Организация  |
|:---:|:-----------:|:-----------:|:-----------:|:---------------------------------------:|:--------------------------:|:-----------:|:---------:|:-----------------------------------------------:|
|  1  |          192.168.1.1                    |      Россия, Москва       |   Роутер    | 
|  2   | 10.224.0.1 |   США, ЛА       |    IANA     |  
|  3   | msk.piter-ix.google.com [31.44.187.11] |     Германия, Франкфурт      | MSK-IX |
|  4 | 108.170.250.83  |   США, Маунтин Вью      | Google LLC | 
|  5     |          216.239.50.2                 | Великобритания | Google LLC  | 
|  6    |          108.170.232.251                  | США, Маунтин Вью | Google LLC  | 
|  7    |         172.253.79.237                 | США, Маунтин Вью | Google LLC  | 
|  8     |        Request timed out.                    |        |        |   
|  9  |         Request timed out.               |                          |       |
|  10   |        Request timed out.               |                            |             |    
|  11 |        Request timed out.               |                            |             |        
|  12    |        Request timed out.               |                            |             |     
|  13 |            Request timed out.               |                            |             |    
|  14      |        Request timed out.               |                            |             |   
|  15| Request timed out.               |                            |             |          
|  16   |        Request timed out.               |                            |             |      
|  17   |       dns.google [8.8.8.8]              |       США, Нью-Йорк        | Google LLC  |    


<h3 align="center"><b>Cloudflare DNS</b></h3>

**Маршрут**


```
>tracert 1.1.1.1

Трассировка маршрута к one.one.one.one [1.1.1.1]
с максимальным числом прыжков 30:

  1    57 ms    13 ms    19 ms  router.asus.com [192.168.1.1]
  2   210 ms    70 ms   113 ms  10.224.0.1
  3     8 ms     6 ms    17 ms  81.200.19.93
  4     6 ms   116 ms    33 ms  bb-m9.westcall.ru [195.94.230.105]
  5    47 ms    17 ms    22 ms  msk-ix.cloudflare.com [195.208.209.7]
  6     3 ms    19 ms    66 ms  one.one.one.one [1.1.1.1]

Трассировка завершена.

```
**Среднее RTT**
```
>ping 1.1.1.1

Обмен пакетами с 1.1.1.1 по с 32 байтами данных:
Ответ от 1.1.1.1: число байт=32 время=93мс TTL=61
Ответ от 1.1.1.1: число байт=32 время=158мс TTL=61
Ответ от 1.1.1.1: число байт=32 время=21мс TTL=61
Ответ от 1.1.1.1: число байт=32 время=4мс TTL=61

Статистика Ping для 1.1.1.1:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 4мсек, Максимальное = 158 мсек, Среднее = 69 мсек
```
Наибольшая временная задержка у 2 узла.

**Местоположение и организация**

|  №    |              Узел                       |     Местоположение      |Организация  |
|:---:|:-----------:|:-----------:|:-----------:|:---------------------------------------:|:--------------------------:|:-----------:|:---------:|:-----------------------------------------------:|
|  1  |          192.168.1.1                    |      Россия, Москва        |   Роутер    | 
|  2   | 10.224.0.1 |     США, Лос-Анжелес     |    IANA     |  
|  3   | 81.200.19.93 |     Россия, Москва       | ИскраТелеком |
|  4 | bb-m9.westcall.ru [195.94.230.105]  |   Россия, Москва      | Westcall | 
|  5     |          msk-ix.cloudflare.com [195.208.209.7]               | Россия, Москва | MSK-IX | 
|  6    |          one.one.one.one [1.1.1.1]                | Австралия | APNIC and Cloudflare DNS | 



<h3 align="center"><b>OpenDNS</b></h3>

**Маршрут**


```
>tracert 146.112.62.105

Трассировка маршрута к opendns.com [146.112.62.105]
с максимальным числом прыжков 30:

  1     2 ms     4 ms     2 ms  router.asus.com [192.168.1.1]
  2     2 ms     1 ms     2 ms  10.224.0.1
  3    14 ms     3 ms     2 ms  81.200.19.93
  4    12 ms     2 ms     2 ms  bb-m9.westcall.ru [195.94.230.105]
  5     9 ms     3 ms     7 ms  msk-m9-cr2.be2237.rascom.as20764.net [80.64.101.76]
  6     *        *        *     Превышен интервал ожидания для запроса.
  7     *        *        *     Превышен интервал ожидания для запроса.
  8     *        *        *     Превышен интервал ожидания для запроса.
  9   131 ms   134 ms   153 ms  4.53.112.158
 10     *        *        *     Превышен интервал ожидания для запроса.
 11     *        *        *     Превышен интервал ожидания для запроса.
 12   139 ms   140 ms   139 ms  opendns.com [146.112.62.105]

Трассировка завершена.

```
**Среднее RTT**
```
>ping 146.112.62.105

Обмен пакетами с 146.112.62.105 по с 32 байтами данных:
Ответ от 146.112.62.105: число байт=32 время=139мс TTL=53
Ответ от 146.112.62.105: число байт=32 время=139мс TTL=53
Ответ от 146.112.62.105: число байт=32 время=139мс TTL=53
Ответ от 146.112.62.105: число байт=32 время=141мс TTL=53

Статистика Ping для 146.112.62.105:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 139мсек, Максимальное = 141 мсек, Среднее = 139 мсек
```
Наибольшая временная задержка на 4 узле.

**Местоположение и организация**

|  №    |              Узел                       |     Местоположение      |Организация  |
|:---:|:-----------:|:-----------:|:-----------:|:---------------------------------------:|:--------------------------:|:-----------:|:---------:|:-----------------------------------------------:|
|  1  |          192.168.1.1                    |      Россия, Ногинск        |   Роутер    | 
|  2   | 10.224.0.1 |     США, Лос-Анжелес       |    IANA     |  
|  3   | 81.200.19.93 |     Россия, Москва       |Flex|
|  4 | bb-m9.westcall.ru [195.94.230.105]  |   Лос-Анжелес, США   | 	IANA | 
|  5     |   msk-m9-cr2.be2237.rascom.as20764.net [80.64.101.76]        |Россия, Ногинск| Flex  | 
|  6    |         Request timed out.                  |       |      | 
|  7    |      Request timed out.                 |     |       | 
|  8     |        Request timed out.                 |       |     	  |   
|  9     |        4.53.112.158                 |    США   |     IPADD5-ARIN	  |
|  10     |        Request timed out.                 |       |     	  |
|  11     |        Request timed out.                 |       |     	  |
|  12     |       opendns.com [146.112.62.105]                 |   Европа    |    OpenDNS 	  |


<h3 align="center"><b>GTS-M</b></h3>

**Маршрут**


```
>tracert 185.8.127.173

Трассировка маршрута к 185.8.127.173 с максимальным числом прыжков 30

  1     2 ms    10 ms     1 ms  router.asus.com [192.168.1.1]
  2     3 ms     2 ms     2 ms  10.224.0.1
  3     3 ms     2 ms     6 ms  185.8.127.173

Трассировка завершена.

```
**Среднее RTT**
```
>ping 185.8.127.173

Обмен пакетами с 185.8.127.173 по с 32 байтами данных:
Ответ от 185.8.127.173: число байт=32 время=14мс TTL=62
Ответ от 185.8.127.173: число байт=32 время=46мс TTL=62
Ответ от 185.8.127.173: число байт=32 время=5мс TTL=62
Ответ от 185.8.127.173: число байт=32 время=15мс TTL=62

Статистика Ping для 185.8.127.173:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 5мсек, Максимальное = 46 мсек, Среднее = 20 мсек
```
Наибольшая временная задержка на 2 узле.

**Местоположение и организация**

|  №    |              Узел                       |     Местоположение      |Организация  |
|:---:|:-----------:|:-----------:|:-----------:|:---------------------------------------:|:--------------------------:|:-----------:|:---------:|:-----------------------------------------------:|
|  1  |          192.168.1.1                    |      Россия, Москва       |   Роутер    | 
|  2   | 10.224.0.1 |     США, Лос-Анжелес      |    IANA     |  
|  3   | 185.8.127.173 |     Россия, Москва       | GTS-M |



<h3 align="center"><b>Сравнительная диаграмма RTT к серверам</b></h3>

Используемые цвета

  * черный - Google DNS 
  * зеленый - Cloudflare DNS 
  * оранжевый - OpenDNS 
  * синий - ГТС 
  
```{r, echo=FALSE}
x <- c(0,10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160)
y <- c(0,0.25,0.5,0.75,1,1.25,1.5,1.75,2,2.25,2.5,2.75,3,3.25,3.5,3.75,4)
x_1 <- c(18,18,20,20)
y_1 <- c(1,2,3,4)
x_2 <- c(93,158,21,4)
y_2 <- c(1,2,3,4)
x_3 <- c(139,139,139,141)
y_3 <- c(1,2,3,4)
x_4 <- c(14,46,5,15)
y_4 <- c(1,2,3,4)
plot(y,x,main = "", xlab = "", ylab = "RTT",type = "n")
points(y_1,x_1, col = "black")
lines(y_1,x_1, col = "black")
points(y_2,x_2, col = "green")
lines(y_2,x_2, col = "green")
points(y_3,x_3, col = "orange")
lines(y_3,x_3, col = "orange")
points(y_4,x_4, col = "blue")
lines(y_4,x_4, col = "blue")
```

**Оценка результатов**

Меньше всего времени потребовалось для обмена пакетов для Google.

**Вывод**

Я ознакомилась с параметром RTT, утилитой tracert и ping.


