```{r}
library(tidyverse)
get_sum_df <- function(company_url) {
  country_state <- NA
  dig <- system2('dig', company_url, stdout = TRUE)
  ip <- dig %>%
    grep(pattern = company_url, value = TRUE) %>%
    str_extract(pattern = "\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b")
  ip <- ip[!is.na(ip)]
  
  whois <- system2('whois', ip[1], stdout = TRUE)
  phones <- whois %>%
    grep(pattern = "Phone", value = TRUE, ignore.case = TRUE) %>%
    str_squish() %>%
    str_split(pattern = " ") %>%
    data.table::transpose() %>%
    .[[2]] %>%
    unique() %>%
    str_c(collapse = " ")
  
  netblock <- whois %>%
    grep(pattern = "CIDR", value = TRUE, ignore.case = TRUE) %>%
    str_squish() %>%
    str_split(pattern = " ", simplify = TRUE) %>%
    .[-1] %>%
    str_c(collapse = " ")
  
  country <- whois %>%
    grep(pattern = "Country",
         value = TRUE,
         ignore.case = TRUE) %>%
    str_squish() %>%
    str_split(pattern = " ", simplify = TRUE) %>%
    .[-1]
  
  country_state <- whois %>%
    grep(pattern = "State",
         value = TRUE,
         ignore.case = TRUE) %>%
    str_squish() %>%
    str_split(pattern = " ", simplify = TRUE) %>%
    .[-1]
  if(length(country_state)==0) country_state <- NA
  
  address <- whois %>%
    grep(pattern = "address",
         value = TRUE,
         ignore.case = TRUE) %>%
    str_squish() %>%
    str_split(pattern = " ", simplify = TRUE) %>%
    .[-1] %>%
    str_c(collapse = " ")
  
  hosting <- whois %>%
    grep(pattern = "Hosting",
         value = TRUE,
         ignore.case = TRUE) %>%
    str_squish() %>%
    str_split(pattern = " ")
  hosting <- lapply(hosting, collapse = " ", str_c) %>%
    str_c(collapse = " ")
  
  nmap <-
    system2('nmap',
            args = c('-p', '22,21,80,443', ip[1]),
            stdout = TRUE)
  ports <- nmap %>%
    grep(pattern = "open",
         value = TRUE,
         ignore.case = TRUE) %>%
    str_squish() %>%
    str_split(pattern = " ") %>%
    data.table::transpose() %>%
    .[[1]] %>%
    str_c(collapse = " ")
  ip <- str_c(ip,collapse = ' ')

  company_sum <-
    data.frame(
      csum = c(
        company_url,
        ip,
        netblock,
        country,
        country_state,
        address,
        phones,
        hosting,
        ports
      ),
      row.names = c(
        'company_url',
        'ip',
        'netblock',
        'country',
        'country_state',
        'address',
        'phones',
        'hosting',
        'ports'
      )
    )
  company_sum
  
}

urls <- c("Eonreality.com", "Amusitronix.com", "Es.com", "Inv3rsion.com", "Vrrentals.com", "Cortona3d.com", "3dwebtech.co.uk", "Metamotion.com", "5dt.com", "Vrtainment.com", "Arsenal.it", "Haptek.com", "Zoomhome.com", "Exitreality.com", "Sensetrix.com")
dfs <- lapply(urls, get_sum_df) # применение полученной функции к вектору, на выходе функции - список из одноколоночных датафреймов
result <- bind_cols(dfs) # объединение в один датафрейм

# задаем названия строк
row.names(result) <- c('company_url',
        'ip',
        'netblock',
        'country',
        'country_state',
        'address',
        'phones',
        'hosting',
        'ports'
      )
# задаем названия столбцов из первой строки полученного датафрейма (предварительно переведя в тип character)
colnames(result) <- map(result[1,],as.character) %>% unlist()
# удалим теперь первую строку таблицы - она дублирует названия столбцов
result <- result[-1,]
# Выводим таблицу
knitr::kable(result)
```

```{r, cache = TRUE}
library(rappalyzer)
rappalyze("Eonreality.com")
rappalyze("Amusitronix.com")
rappalyze("Es.com")
rappalyze("Inv3rsion.com")
rappalyze("Vrrentals.com")
rappalyze("Cortona3d.com")
rappalyze("3dwebtech.co.uk")
rappalyze("Metamotion.com")
rappalyze("5dt.com")
rappalyze("Vrtainment.com")
rappalyze("Arsenal.it")
rappalyze("Haptek.com")
rappalyze("Zoomhome.com")
rappalyze("Exitreality.com")
rappalyze("Sensetrix.com")
```

